version: '2'
services:
  zookeeper:
    image: sumglobal/rpi-zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "49154:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.155
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock