version: '2'

services:
  node-chat:
    image: node-chat:1
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3000:3000"